# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: federated_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66\x65\x64\x65rated_model.proto\"T\n\x12ModelUpdateRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0cmodel_update\x18\x02 \x03(\x02\x12\x15\n\rweight_shapes\x18\x03 \x03(\x05\"\"\n\x13ModelUpdateResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\"\x13\n\x11ModelStatsRequest\"4\n\x12ModelStatsResponse\x12\x10\n\x08\x61\x63\x63uracy\x18\x01 \x01(\x02\x12\x0c\n\x04loss\x18\x02 \x01(\x02\".\n\x19\x43lientContributionRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"E\n\x1a\x43lientContributionResponse\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontribution\x18\x02 \x01(\x05\"\'\n\x11PredictionRequest\x12\x12\n\ninput_data\x18\x01 \x03(\x02\"$\n\x12PredictionResponse\x12\x0e\n\x06result\x18\x01 \x03(\x02\x32\x8d\x02\n\x11\x46\x65\x64\x65ratedLearning\x12\x38\n\x0bUpdateModel\x12\x13.ModelUpdateRequest\x1a\x14.ModelUpdateResponse\x12\x38\n\rGetModelStats\x12\x12.ModelStatsRequest\x1a\x13.ModelStatsResponse\x12P\n\x15GetClientContribution\x12\x1a.ClientContributionRequest\x1a\x1b.ClientContributionResponse\x12\x32\n\x07Predict\x12\x12.PredictionRequest\x1a\x13.PredictionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MODELUPDATEREQUEST']._serialized_start=25
  _globals['_MODELUPDATEREQUEST']._serialized_end=109
  _globals['_MODELUPDATERESPONSE']._serialized_start=111
  _globals['_MODELUPDATERESPONSE']._serialized_end=145
  _globals['_MODELSTATSREQUEST']._serialized_start=147
  _globals['_MODELSTATSREQUEST']._serialized_end=166
  _globals['_MODELSTATSRESPONSE']._serialized_start=168
  _globals['_MODELSTATSRESPONSE']._serialized_end=220
  _globals['_CLIENTCONTRIBUTIONREQUEST']._serialized_start=222
  _globals['_CLIENTCONTRIBUTIONREQUEST']._serialized_end=268
  _globals['_CLIENTCONTRIBUTIONRESPONSE']._serialized_start=270
  _globals['_CLIENTCONTRIBUTIONRESPONSE']._serialized_end=339
  _globals['_PREDICTIONREQUEST']._serialized_start=341
  _globals['_PREDICTIONREQUEST']._serialized_end=380
  _globals['_PREDICTIONRESPONSE']._serialized_start=382
  _globals['_PREDICTIONRESPONSE']._serialized_end=418
  _globals['_FEDERATEDLEARNING']._serialized_start=421
  _globals['_FEDERATEDLEARNING']._serialized_end=690
# @@protoc_insertion_point(module_scope)
