# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import federated_model_pb2 as federated__model__pb2


class FederatedLearningStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateModel = channel.unary_unary(
                '/FederatedLearning/UpdateModel',
                request_serializer=federated__model__pb2.ModelUpdateRequest.SerializeToString,
                response_deserializer=federated__model__pb2.ModelUpdateResponse.FromString,
                )
        self.GetModelStats = channel.unary_unary(
                '/FederatedLearning/GetModelStats',
                request_serializer=federated__model__pb2.ModelStatsRequest.SerializeToString,
                response_deserializer=federated__model__pb2.ModelStatsResponse.FromString,
                )
        self.GetClientContribution = channel.unary_unary(
                '/FederatedLearning/GetClientContribution',
                request_serializer=federated__model__pb2.ClientContributionRequest.SerializeToString,
                response_deserializer=federated__model__pb2.ClientContributionResponse.FromString,
                )
        self.Predict = channel.unary_unary(
                '/FederatedLearning/Predict',
                request_serializer=federated__model__pb2.PredictionRequest.SerializeToString,
                response_deserializer=federated__model__pb2.PredictionResponse.FromString,
                )


class FederatedLearningServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientContribution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedLearningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModel,
                    request_deserializer=federated__model__pb2.ModelUpdateRequest.FromString,
                    response_serializer=federated__model__pb2.ModelUpdateResponse.SerializeToString,
            ),
            'GetModelStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelStats,
                    request_deserializer=federated__model__pb2.ModelStatsRequest.FromString,
                    response_serializer=federated__model__pb2.ModelStatsResponse.SerializeToString,
            ),
            'GetClientContribution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientContribution,
                    request_deserializer=federated__model__pb2.ClientContributionRequest.FromString,
                    response_serializer=federated__model__pb2.ClientContributionResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=federated__model__pb2.PredictionRequest.FromString,
                    response_serializer=federated__model__pb2.PredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FederatedLearning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FederatedLearning(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederatedLearning/UpdateModel',
            federated__model__pb2.ModelUpdateRequest.SerializeToString,
            federated__model__pb2.ModelUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModelStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederatedLearning/GetModelStats',
            federated__model__pb2.ModelStatsRequest.SerializeToString,
            federated__model__pb2.ModelStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClientContribution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederatedLearning/GetClientContribution',
            federated__model__pb2.ClientContributionRequest.SerializeToString,
            federated__model__pb2.ClientContributionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederatedLearning/Predict',
            federated__model__pb2.PredictionRequest.SerializeToString,
            federated__model__pb2.PredictionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
